### ISSUE TITLE
How do you make quick modifications to your config?

### ISSUE THREAD

**Issue by codygman** [vlaci/nix-doom-emacs#11]
nix-build isn't the quickest and I found I'm less likely to add things to my ~/.emacs.d as a result. I think I'm going to use the workaround of having something like a incubating-features.el file or something I load where I can quickly add things to my config and not have to wait for nix-build everytime I want to change my config.

How do you handle this issue?

**Comment by vlaci** [comment]
Most of the time I try configuration modifications interactively in emacs itself. Loading a custom configuration from outside of the nix store via a `(load ...)` directive in your `config.el` as you mentioned is probably the easiest workaround for your case.

Having the ability to easily roll-back to a known working emacs installations trumps the inconvenience of nix build for me.
