### ISSUE TITLE
flyspell is broken in nix-doom-emacs but not in doom-emacs

### ISSUE THREAD

**Issue by Mic92** [vlaci/nix-doom-emacs#133]
When using upstream doom-emacs, flyspell is functional.
Using nix-doom-emacs the following error appears:

```
$ emacs ./foo.sh
# M-x flycheck-mode
Error while checking syntax automatically: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
```

I tried to get a backtrace with `M-: (setq debug-on-error t)` but it did not work. I would assume that this error is also reproducible for other folks. I am currently on b182af7d10aa8394f12ecc2c53fd942fa30de060

**Comment by vlaci** [comment]
Unfortunately I could not reproduce the error using my configuration.

**Comment by Mic92** [comment]
Thanks. That's good starting point. I try a more minimal configuration.

**Comment by Mic92** [comment]
Nevermind. This was a bug introduced by my configuration.
