### ISSUE TITLE
Unexpected error when integrating with home-manager

### ISSUE THREAD

**Issue by jackmac92** [vlaci/nix-doom-emacs#15]
Hey, really interested in this project, but not that familiar with nix yet. I'm running into the following error when trying to integrate with home-manager (following the README). This is the error I get with `home-manager build`

`cp: missing destination file operand after '/nix/store/1299vx9xbq694rzx2jh4prb8i8dfwrdk-doom-private'`

More of the error below in case that helps
```
building '/nix/store/ynprix94nrlk38naiy2ciqwhz2gz6q7w-doom-private.drv'...
cp: missing destination file operand after '/nix/store/1299vx9xbq694rzx2jh4prb8i8dfwrdk-doom-private'
Try 'cp --help' for more information.
builder for '/nix/store/ynprix94nrlk38naiy2ciqwhz2gz6q7w-doom-private.drv' failed with exit code 1
cannot build derivation '/nix/store/5ljdbmgwqr57vb4613b9ldzaxq4z5pz3-doom-emacs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h0k33wxvsrkqgxrc1q2cd1xh8pzkm2wb-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/255gyxb059mm0aqj54azvdm6jvc4j6s1-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/255gyxb059mm0aqj54azvdm6jvc4j6s1-home-manager-generation.drv' failed
```

This is my `home.nix`

```
{ config, pkgs, ... }:

let
 doom-emacs = pkgs.callPackage (builtins.fetchTarball {
   url = https://github.com/vlaci/nix-doom-emacs/archive/master.tar.gz;
 }) {
   doomPrivateDir = "/home/jmccown/doom.d";  # Directory containing your config.el init.el
                               # and packages.el files
 };
in {
  programs.home-manager.enable = true;
  home.username = "jmccown";
  home.homeDirectory = "/home/jmccown";
  home.stateVersion = "20.09";
  home.packages = [ doom-emacs ];
  home.file.".emacs.d/init.el".text = ''
    (load "default.el")
  '';

}
```
I had to adjust `doomPrivateDir` by wrapping it in quotes, and to use the full path. Any tips would be appreciated!

**Comment by vlaci** [comment]
If you've used relative paths it should be relative to the location of your `home.nix` or the `.nix` file where the `callPackage` call is placed.

**Comment by jackmac92** [comment]
Hmm yea I think it's related to how I'm using a symlink for my `~/.doom.d` folder (I had forgotten I was doing this, helps for managing config via chezmoi). I'll try to dig into it some more later. Thanks for your response!
