### ISSUE TITLE
How to customize the doom package? 

### ISSUE THREAD

**Issue by JonathanReeve** [vlaci/nix-doom-emacs#159]
I'd like to use [my own fork of doom-emacs](https://github.com/jonathanreeve/doom-emacs), since the main branch is slow to merge pull requests, and I'm eager to use new features like [bibliographic management](https://github.com/hlissner/doom-emacs/pull/2888). Is there a way to do that using nix-doom-emacs? Some kind of overlay?

**Comment by vlaci** [comment]
You can use the override mechanism in [flakes](https://nixos.wiki/wiki/Flakes#Input_schema) or if not using flakes you can override `doom-emacs` with via the `dependencyOverrides` argument: https://github.com/vlaci/nix-doom-emacs/blob/master/default.nix#L43-L55

**Comment by JonathanReeve** [comment]
Awesome, thanks.
