### ISSUE TITLE
Failed to load package incrementally, because: (file-error Creating directory Permission denied)

### ISSUE THREAD

**Issue by kylegentle** [vlaci/nix-doom-emacs#18]
Hi vlaci,

Thanks for making this project! I'm moving more of my configuration into Nix every day, and having doom is a huge win 😄 

Upon running emacs after installation, it seems that emacs is attempting to modify files in the nix store, leading to lots of permissions errors, and breaking basic functionality like loading files and quitting emacs. Here are some details on my setup, and the errors from emacs:

**Platform**: Darwin, OS X Catalina
**nixpkgs version**: 20.09pre224406.5f14d99efed
```
Loading /nix/store/7kka593zlhc15mhjmwrjw0pilkdq4p3j-emacs-26.3/share/emacs/site-lisp/site-start.el (source)...done
Loading /nix/store/gbp4jdhqzbsardb4cfmy2m219bnbrv6r-emacs-packages-deps/share/emacs/site-lisp/default.el (source)...
doom-emacs is not placed in ‘doom-private-dir’,
loading from ‘site-lisp’
Loading /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/init.el (source)...done
Loading /nix/store/gbp4jdhqzbsardb4cfmy2m219bnbrv6r-emacs-packages-deps/share/emacs/site-lisp/default.el (source)...done
Doom loaded 221 packages across 41 modules in 1.065s
Error running timer ‘require’: (file-error "Creating directory" "Permission denied" "/nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server")
Failed to load with-editor package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load git-commit package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load magit package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load org package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load org-agenda package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load org-capture package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load org package incrementally, because: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
Failed to load deferred package server: (file-error Creating directory Permission denied /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server)
files--ensure-directory: Creating directory: Permission denied, /nix/store/fkdslkcl0j4pkzmkf1151pizpjsvsjn2-doom-emacs/server
```

My configuration is almost identical to the example in this repo, save for pinning a specific sha256 hash for the current version. Is there other information I can provide that would be helpful?

**Comment by kylegentle** [comment]
I was able to replicate this on my NixOS installation, using nixpkgs version nixos-20.03.

**Comment by vlaci** [comment]
Could you share your configuration?

**Comment by kylegentle** [comment]
Sure thing, here's a repo: https://gitlab.com/kylegentle/nix-home/

On my Macbook, configuration.nix is unused, and the repo lives in ~/.config/nixpkgs. On my NixOS install, it lives in ~/dev/nix, which is symlinked to /etc/nixos. home.nix varies slightly between those two machines, mainly in whether the darwin-specific modules are imported.

**Comment by vlaci** [comment]
`server.el` wants to create this directory when `server-use-tcp` is set to true to contain authentication information. The location used can be customized via `server-auth-dir` variable. The default is unfortunately `(locate-user-emacs-file "server/")`. I don't know if I can do something about that other than maybe extending the documentation with module specific quirks.

**Comment by kylegentle** [comment]
That's very helpful, thank you! I'll try customizing `server-auth-dir` to a writable location and see if that resolves the issue.

**Comment by kylegentle** [comment]
Confirmed that emacs no longer attempts to write to the Nix store after setting `server-auth-dir` to a directory outside the store. Thanks again for your help!
