### ISSUE TITLE
LaTeX module fails

### ISSUE THREAD

**Issue by ulysses4ever** [vlaci/nix-doom-emacs#183]
When I enable the `latex` module (in `init.el`), `home-manager switch` fails with

```bash
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download auctex-13.0.4.tar from any mirror
builder for '/nix/store/gncy9prfphsky7q6h26x8v91b20fp9g9-auctex-13.0.4.tar.drv' failed with exit code 1
building '/nix/store/bad5n8dk0g8j43nyghqfsj8d0i594nl8-bash-completion-recipe.drv'...
cannot build derivation '/nix/store/63jqd881242fchk613s57and2iqpzglx-emacs-auctex-13.0.4.drv': 1 dependencies couldn't be built
```

I'm not sure if this is the right place to report it, but maybe you have any idea how to deal with it or where it's better to report. I'm on NixOS (unstable) if it matters.

**Comment by vlaci** [comment]
Related issue in emacs-overlay: https://github.com/nix-community/emacs-overlay/issues/125

**Comment by Mic92** [comment]
Please check if this is still an issue.

**Comment by ulysses4ever** [comment]
For some reason, if I just enable the latex module in Doom config and do `home-manager switch`, it still fails trying to download the same auctex-13.0.4. Not sure what and where to update so that I get the current overlay version (13.0.6).

**Comment by Mic92** [comment]
Is this maybe out-of-date: https://github.com/vlaci/nix-doom-emacs/blob/51645030623075a50f0f2fb8e95d113336fa109f/flake.lock#L36

**Comment by vlaci** [comment]
Newer emacs-overlay contains a few broken package (at least for my configuration):
https://github.com/vlaci/nix-doom-emacs/pull/190 (failing build: https://github.com/vlaci/nix-doom-emacs/runs/2309843344)

You can try using nix-doom-emacs from this commit for updated emacs-overlay https://github.com/vlaci/nix-doom-emacs/commit/c0e82d14bf22414d5879f61555678f9d9ecef1db

**Comment by ulysses4ever** [comment]
@vlaci thanks for the heads-up! I happen to depend on `emacs-spell-fu`, so this commit fails for me too. If you feel like it, close the issue. I'd certainly prefer to have it open until emacs-overlay unbreaks and nix-doom-emacs switches to the newer version, but it's up to you. Thanks a lot for your feedback!

**Comment by vlaci** [comment]
Should be fixed on `develop` branch after the latest `emacs-overlay` update Will merge to master if I find it stable in the coming days.

**Comment by vlaci** [comment]
Builds fine for me using the last couple of `emacs-overlay` updates
