### ISSUE TITLE
doom-snippets-dir doesn't contain snippets

### ISSUE THREAD

**Issue by badly-drawn-wizards** [vlaci/nix-doom-emacs#19]
I expect that with `doom-snippets` loaded, I should have those snippets available. The variable of locations to search for snippets `yas/snippet-dirs` indeed contains `doom-snippets-dir`, but when I look at the contents of that directory (inside the straight-emacs-env in the nix store), it doesn't have any of the snippets. It does however have the compiled elisp source.

If anyone can point me in the general direction of how to hotpatch this, it would be appreciated.

**Comment by vlaci** [comment]
Fixed in #24
