### ISSUE TITLE
Add sample .doom.d files to help getting started

### ISSUE THREAD

**Issue by joonazan** [vlaci/nix-doom-emacs#2]
It would be helpful if new users could download an example config. I had to get the defaults from doom-emacs and then add the following to packages.el:

```Emacs Lisp
(package! rotate-text :disable t)
(package! doom-snippets :disable t)
```

**Comment by vlaci** [comment]
The needed package depends on one's `init.el` file that's why I missed this issue. I have started to add custom packages needed by doom to the derivation. I am planning to add these missing bits too.

**Comment by vlaci** [comment]
Should be fixed on develop branch. Will merge to master after it is prone to be stable for me in a few days.

**Comment by joonazan** [comment]
Ah, so it's possible to use those packages. That's great!

**Comment by joonazan** [comment]
Tried develop. It works.
