### ISSUE TITLE
Adding custom packages

### ISSUE THREAD

**Issue by Mic92** [vlaci/nix-doom-emacs#20]
I have some packages that are not in melpa that I want to add:

https://github.com/Mic92/osc52

and 

https://github.com/Mic92/company-tmux

Is there a way to add them?

**Comment by vlaci** [comment]
I'd be open to change the interface to pass in additional derivations during build. Currently the only option is to override `emacsPackages` which is not straightforward and incompatible with locking... I'd definitely want to rework the input parameters of this derivation as using a custom emacs derivation also suffers from this issue.
I don't know if those packages should be added in this project which are not explicitly dependencies for doom's builtin modules. I am open to that if we cannot come up with an alternative straightforward solution.

**Comment by Mic92** [comment]
It turns out that I actually don't need them anymore. Doom comes with clipetty and company-tmux did not really work for me.
