### ISSUE TITLE
How to run doom terminal commands

### ISSUE THREAD

**Issue by Cmdv** [vlaci/nix-doom-emacs#25]
I'm trying to be able to run command like `doom refresh` / `doom upgrade`.

But `bin/doom` isn't on my path so thought I would try to run it from where home-manager put it:

```
> /nix/store/rp33wjass23hkxvcqwa2bm91xclhydbk-doom-emacs/bin/doom refresh
```
which returns:
```
Failed to run "git"; see buffer *straight-process*
Error in kill-emacs-hook (straight--transaction-finalize): (file-error "Opening output file" "Permission denied" "/nix/store/adi936x1004lbqmdpdhjn08jh5p6pvb9-straight-emacs-env/straight/build-cache.el")
```
Which obviously indicates that's a terrible way to do it!!

What would be a way to accomplish this?

**Comment by vlaci** [comment]
The only way to update doom is through the nix expression. I am working on some GitHub actions that would provide regular updates to doom and its dependencies.

**Comment by Cmdv** [comment]
@vlaci ah cool what expression would I need to use? just if I update my `init.el` I'd need to `doom build`. I've tried `home-manager switch` but obviously that doesn't work. 😄

**Comment by vlaci** [comment]
if you are updating `init.el` in the directory pointed by `doomPrivateDir` then home-manager switch should rebuild doom-emacs with the new configuration.
