### ISSUE TITLE
Can't specify a different branch with `package!`

### ISSUE THREAD

**Issue by JonathanReeve** [vlaci/nix-doom-emacs#259]
I'm trying to test out the v2 branch of org-roam, with this in my packages.el: 

```elisp
(package! org-roam :recipe (:host github :repo "org-roam/org-roam" :branch "v2"))
```

But while it seems to download org-roam, it's still on the v1 branch.

**Comment by vlaci** [comment]
This derivation doesn't use the original sources during build but emacs-overlay by default. You can override the inputs using the usual nix way: https://github.com/vlaci/nix-doom-emacs/blob/f2849e51a557b78214ab19bb504fb936d8d513d4/default.nix#L38

**Comment by JonathanReeve** [comment]
Ah OK, cool, thanks!
