### ISSUE TITLE
The option doom-emacs.dependencyOverrides does not exist

### ISSUE THREAD

**Issue by b1tg** [vlaci/nix-doom-emacs#272]
Hi,
i try to use option `dependencyOverrides` in flake.nix base on the example in README.md
```nix
#[..]
    programs.doom-emacs = {
      enable = true;
      doomPrivateDir = /root/doom.d;
      dependencyOverrides = {

      };
    };
#[..]
```

but got errors:

```sh
[root@nixos:~]# nixos-rebuild switch --flake '/etc/nixos#root' --impure
building the system configuration...
error: The option `home-manager.users.root.programs.doom-emacs.dependencyOverrides' does not exist. Definition values:
       - In `<unknown-file>': { }
(use '--show-trace' to show detailed location information)
error: getting status of '/tmp/nixos-rebuild.e1CdFG/result': No such file or directory

[root@nixos:~]# 
```

**Comment by Patryk27** [comment]
Try doing something in the lines of:
```nix
{ pkgs, ... }: {
  programs.doom-emacs = {
    enable = true;
    doomPrivateDir = /root/doom.d;

    package = doom-emacs.override {
      dependencyOverrides = {
        # ...
      };
    };
  };
}
```
The thing is that `dependencyOverrides` is a parameter for the package function (https://github.com/vlaci/nix-doom-emacs/blob/3893c50877a9d2d5d4aeee524ba1539f22115f1f/default.nix#L55), not the home-manager module 🙂

**Comment by b1tg** [comment]
I try this but not work, the built Emacs still without Xwidgets support, then i deliberately change the `withXwidgets` to a wrong option like `abcxxx`, nixos-rebuild without error, seems like this option was ignored.
```nix
            programs.doom-emacs = {                                                
              enable = true;                                                       
              doomPrivateDir = /root/doom.d;                                       
                                                                                   
              package = pkgs.doom-emacs.override {                                 
                dependencyOverrides = {                                            
                  withXwidgets = true;                                             
                  # ...                                                            
                };                                                                 
              };                                                                   
            };  

```

**Comment by Patryk27** [comment]
From what I see, `dependencyOverrides` is meant for overriding the [nix-doom-emacs's dependencies](https://github.com/vlaci/nix-doom-emacs/blob/fee14d217b7a911aad507679dafbeaa8c1ebf5ff/flake.nix#L38) - i.e. if you don't want to wait until nix-doom-emacs gets its emacs-overlay updated, you can do:
```nix
{
  dependencyOverrides = {
    emacs-overlay = pkgs.fetchFromGithub ...;
  };
}
```

On the other hand, what you're trying to achieve is to modify the emacs's package _itself_ - for that, something like this should work:
```nix
{ ... }: {
  programs.doom-emacs = {
    emacsPackage = pkgs.emacs.override {
      withXwidgets = true;
    };
  };
};
```
... where this `withXwidgets` parameter this time correctly refers to https://github.com/NixOS/nixpkgs/blob/8f40f574f863e93260c906d5ea73c08eae589bad/pkgs/applications/editors/emacs/generic.nix#L21 🙂

**Comment by b1tg** [comment]
It works now! Thanks for your help @Patryk27
