### ISSUE TITLE
File is missing: Cannot open load file, no such file or directory. use-package-core

### ISSUE THREAD

**Issue by 0x450x6c** [vlaci/nix-doom-emacs#300]
Hello.

The error appears when using the nix-doom-emacs with the latest emacs-overlay.

Here is minimal [flake.nix](https://github.com/0x450x6c/nix-doom-emacs-example/blob/master/flake.nix) to reproduce:
```
nix build -L 'git+ssh://git@github.com/0x450x6c/nix-doom-emacs-example?branch=master#emacs'
./result/bin/emacs --debug-init
```

---
It seems load-path contains wrong directory for elpa packages.

**Comment by ulysses4ever** [comment]
I hope this fix will also fix #250
