### ISSUE TITLE
Can't use elfeed

### ISSUE THREAD

**Issue by ericmoritz** [vlaci/nix-doom-emacs#45]
Whenever I try to run `elfeed` I get the following error:

```
files--ensure-directory: Creating directory: Read-only file system, /nix/store/p4pw45p5zcn84j92rrc7w434llipqn5i-straight-emacs-env/elfeed
```

My doom config is here: https://github.com/ericmoritz/dotfiles/tree/master/dotfiles/.config/nixpkgs/doom.d

**Comment by ericmoritz** [comment]
Sorry for the comment spam, I suppose patching this would work https://github.com/hlissner/doom-emacs/blob/develop/modules/app/rss/config.el#L21-L22

**Comment by vlaci** [comment]
Hm, I am thinking to raise this issue upstream as I think volatile files like `elfeed`'s db should be in `doom-cache-dir`which I already set to be outside of nix store.
In the meantime I made this change in `nix-doom-emacs`. Could you try a build from `develop` branch?

**Comment by ericmoritz** [comment]
The latest develop did work for me. 

It does seem like Doom's rss module is using the wrong value for its default. It should be either `doom-etc-dir` or `doom-cache-dir` based on the comments for those values https://github.com/hlissner/doom-emacs/blob/8f64a0eb31a85952950f5065ecdd493e038ca5cd/core/core.el#L102-L111
