### ISSUE TITLE
Elfeed Install Error

### ISSUE THREAD

**Issue by nglen** [vlaci/nix-doom-emacs#5]
I just converted my installation to use this package however I noticed that whenever **Elfeed** is installed it fails with the following error:
```
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "elfeed"
    (error "Invalid version syntax: `/nix/store/yzgyaf57lmpazm0air4ra8f6132i9d5p-emacs-26.3/bin/emacs: /nix/store/pv3swbphpglpr155mali0r241n92v9g1-git/bin/git: Exec format error' (must start with a number)")
    "/dev/null
    "
```

Following this error, I determined something was calling the **git** stub that you provide. Replacing it with the real version changed the error but didn't fix the underlying issue. The reason for the exec error is because the stub is actually invalid. It both lacks a shebang line and is improperly quoted. Applying the following patch fixed that and allowed me to see the command being run.
```patch
diff --git a/default.nix b/default.nix
index abf9cf5..ced4a65 100644
--- a/default.nix
+++ b/default.nix
@@ -49,7 +49,7 @@
 , runCommand
 , fetchFromGitHub
 , substituteAll
-, writeScriptBin
+, writeShellScriptBin
 , writeTextDir }:
 
 let
@@ -163,8 +163,8 @@ let
 
       # I don't know why but byte-compilation somehow triggers Emacs to look for
       # the git executable. It does not seem to be executed though...
-      git = writeScriptBin "git" ''
-        >&2 echo Executing git is not allowed; command line: "$@"
+      git = writeShellScriptBin "git" ''
+        >&2 echo "Executing git is not allowed; command line:" "$@"
       '';
     in (straight-env.emacsEnv {
       inherit packages;
```

```
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "elfeed"
    (error "Invalid version syntax: `Executing git is not allowed; command line: describe --match=release* --abbrev=0 HEAD' (must start with a number)")
    "/dev/null
    "
```

This call appears to occur within [straight.el](https://github.com/raxod502/straight.el/blob/ed54b626b0faec36fdaff30c72351d5fb41a6786/straight.el#L5812-L5817) and is there as a hacky workaround linked to an [issue](https://github.com/raxod502/straight.el/issues/211) for installing org-mode. Why this shows up for Elfeed but not org-mode, I don't know. There appears to be a variable `straight-fix-org` that you can set to `nil` to disable it which is what [doom-emacs](https://github.com/hlissner/doom-emacs/blob/10623868b8be7673fac765bb2ac6191ca44c344e/core/core-packages.el#L117) does. You appear to have already done something to deal with the original issue in the org-mode package itself [here](https://github.com/vlaci/nix-doom-emacs/blob/master/default.nix#L92-L96) anyway.

**Comment by vlaci** [comment]
Thank you for the detailed bug report!

The problem was caused by elfeed using the override `(org-release)` function set by `straight`. It should have been overriden by doom, as you said, but it was not because my `nix-straight.el` adapter loaded `straight` before `doom` hence it was too late to customizing the value `straight-fix-org`

This should be fixed on the `master` branch now.

**Comment by nglen** [comment]
Thanks for the quick response and fix.

I can confirm it is working now so I'll go ahead and close the issue.
