### ISSUE TITLE
file-missing "Cannot open load file" "No such file or directory" "/nix/store/9mvzb6xvd4xz0ixrd3ljj0ssjz60csan-doom.d/core/core")

### ISSUE THREAD

**Issue by happysalada** [vlaci/nix-doom-emacs#53]
Here is the full stack trace
 
```
[nix-doom-emacs] Advising doom installer to gather packages to install...
Loading /nix/store/p6bdiwjn1vnl4wj9riz25yskpzbjyd9d-doom-src/bin/doom...
Error in private config: "init.el", (file-missing "Cannot open load file" "No such file or directory" "/nix/store/9mvzb6xvd4xz0ixrd3ljj0ssjz60csan-doom.d/core/core")
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------- nix-build
builder for '/nix/store/zkrvjk77g5c5dyqkw4dfq0spsy545ar5-emacs-straight-packages.json.drv' failed with exit code 255
(use '--show-trace' to show detailed location information)
```

I have taken the init.el from the latest doom-emacs master.
Here it is for reference
```
;;; init.el -*- lexical-binding: t; -*-
;;
;; Author:  Henrik Lissner <henrik@lissner.net>
;; URL:     https://github.com/hlissner/doom-emacs
;;
;;   =================     ===============     ===============   ========  ========
;;   \\ . . . . . . .\\   //. . . . . . .\\   //. . . . . . .\\  \\. . .\\// . . //
;;   ||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\/ . . .||
;;   || . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||
;;   ||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||
;;   || . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\ . . . . ||
;;   ||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\_ . .|. .||
;;   || . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\ `-_/| . ||
;;   ||_-' ||  .|/    || ||    \|.  || `-_|| ||_-' ||  .|/    || ||   | \  / |-_.||
;;   ||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \  / |  `||
;;   ||    `'         || ||         `'    || ||    `'         || ||   | \  / |   ||
;;   ||            .===' `===.         .==='.`===.         .===' /==. |  \/  |   ||
;;   ||         .=='   \_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \/  |   ||
;;   ||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \/  |   ||
;;   ||   .=='    _-'          '-__\._-'         '-_./__-'         `' |. /|  |   ||
;;   ||.=='    _-'                                                     `' |  /==.||
;;   =='    _-'                                                            \/   `==
;;   \   _-'                                                                `-_   /
;;    `''                                                                      ``'
;;
;; These demons are not part of GNU Emacs.
;;
;;; License: MIT

;; A big contributor to startup times is garbage collection. We up the gc
;; threshold to temporarily prevent it from running, then reset it later by
;; enabling `gcmh-mode'. Not resetting it will cause stuttering/freezes.
(setq gc-cons-threshold most-positive-fixnum)

;; In noninteractive sessions, prioritize non-byte-compiled source files to
;; prevent the use of stale byte-code. Otherwise, it saves us a little IO time
;; to skip the mtime checks on every *.elc file.
(setq load-prefer-newer noninteractive)

(let (file-name-handler-alist)
  ;; Ensure Doom is running out of this file's directory
  (setq user-emacs-directory (file-name-directory load-file-name)))

;; Load the heart of Doom Emacs
(load (concat user-emacs-directory "core/core")
      nil 'nomessage)

;; And let 'er rip!
(doom-initialize)
```

**Comment by vlaci** [comment]
You need to use [`init.example.el`](https://github.com/hlissner/doom-emacs/blob/develop/init.example.el) from doom and name it as `init.el` in your private configuration.

**Comment by happysalada** [comment]
Sorry about the dumb mistake, thanks for the help!

**Comment by Arnaud954** [comment]
> Here is the full stack trace
> 
> ```
> [nix-doom-emacs] Advising doom installer to gather packages to install...
> Loading /nix/store/p6bdiwjn1vnl4wj9riz25yskpzbjyd9d-doom-src/bin/doom...
> Error in private config: "init.el", (file-missing "Cannot open load file" "No such file or directory" "/nix/store/9mvzb6xvd4xz0ixrd3ljj0ssjz60csan-doom.d/core/core")
> error: --- Error ------------------------------------------------------------------------------------------------------------------------------------- nix-build
> builder for '/nix/store/zkrvjk77g5c5dyqkw4dfq0spsy545ar5-emacs-straight-packages.json.drv' failed with exit code 255
> (use '--show-trace' to show detailed location information)
> ```
> 
> I have taken the init.el from the latest doom-emacs master.
> Here it is for reference
> 
> ```
> ;;; init.el -*- lexical-binding: t; -*-
> ;;
> ;; Author:  Henrik Lissner <henrik@lissner.net>
> ;; URL:     https://github.com/hlissner/doom-emacs
> ;;
> ;;   =================     ===============     ===============   ========  ========
> ;;   \\ . . . . . . .\\   //. . . . . . .\\   //. . . . . . .\\  \\. . .\\// . . //
> ;;   ||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\/ . . .||
> ;;   || . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||
> ;;   ||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||
> ;;   || . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\ . . . . ||
> ;;   ||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\_ . .|. .||
> ;;   || . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\ `-_/| . ||
> ;;   ||_-' ||  .|/    || ||    \|.  || `-_|| ||_-' ||  .|/    || ||   | \  / |-_.||
> ;;   ||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \  / |  `||
> ;;   ||    `'         || ||         `'    || ||    `'         || ||   | \  / |   ||
> ;;   ||            .===' `===.         .==='.`===.         .===' /==. |  \/  |   ||
> ;;   ||         .=='   \_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \/  |   ||
> ;;   ||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \/  |   ||
> ;;   ||   .=='    _-'          '-__\._-'         '-_./__-'         `' |. /|  |   ||
> ;;   ||.=='    _-'                                                     `' |  /==.||
> ;;   =='    _-'                                                            \/   `==
> ;;   \   _-'                                                                `-_   /
> ;;    `''                                                                      ``'
> ;;
> ;; These demons are not part of GNU Emacs.
> ;;
> ;;; License: MIT
> 
> ;; A big contributor to startup times is garbage collection. We up the gc
> ;; threshold to temporarily prevent it from running, then reset it later by
> ;; enabling `gcmh-mode'. Not resetting it will cause stuttering/freezes.
> (setq gc-cons-threshold most-positive-fixnum)
> 
> ;; In noninteractive sessions, prioritize non-byte-compiled source files to
> ;; prevent the use of stale byte-code. Otherwise, it saves us a little IO time
> ;; to skip the mtime checks on every *.elc file.
> (setq load-prefer-newer noninteractive)
> 
> (let (file-name-handler-alist)
>   ;; Ensure Doom is running out of this file's directory
>   (setq user-emacs-directory (file-name-directory load-file-name)))
> 
> ;; Load the heart of Doom Emacs
> (load (concat user-emacs-directory "core/core")
>       nil 'nomessage)
> 
> ;; And let 'er rip!
> (doom-initialize)
> ```

**Comment by vlaci** [comment]
@Arnaud954 do you have the same issue?
