### ISSUE TITLE
Unable to close emacs properly.

### ISSUE THREAD

**Issue by Catvert** [vlaci/nix-doom-emacs#60]
Hey !

When I try to close doom-emacs, via for example :q or SPC-q-q, emacs doesn't want to close because of a read-only problem. 

Here is the error displayed in the statusbar :

```
Creating directory: Read-only file-system, /nix/store/{hash}-doom-emacs/var
```

I am then forced to throw a 'pkill -9 emacs'.

**Comment by vlaci** [comment]
It should be because a package wants to write to the nix store upon exiting emacs. Could you share your configuration?

**Comment by Catvert** [comment]
Indeed, the 'prescient.el' package caused the problem. I deactivated it for the moment, but I saw that there was a way to prevent the save in the options of this package.

Thanks for your help!
