### ISSUE TITLE
Rebuilds on each flake switch

### ISSUE THREAD

**Issue by pltanton** [vlaci/nix-doom-emacs#62]
Each time I execute `nixos-rebuild --flake ... switch` doom-emacs rebuilds itself even if no files from doom.d changed. 
(of course if something else in flake changed)

Is this expected behavior, or did I do something wrong?

**Comment by vlaci** [comment]
Something in the input dependencies should have changed or there is some caching issue in flake handling. Issuing repetitive `nix-build` calls in the repository, e.g. `nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { doomPrivateDir = ../doom.d; }' --no-out-link` does not cause a rebuild for me. I am quite baffled why it is happening when using flakes.

**Comment by vlaci** [comment]
I have reproduced the issue in a VM where I am also using flakes.

**Comment by vlaci** [comment]
It seems to me that the problem goes away if you pass the value to `doomPrivateDir` through the `inputs` attribute set, e.g:

```nix
{
  inputs = {
    home-manager.url = "github:rycee/home-manager";
    nix-doom-emacs.url = "github:vlaci/nix-doom-emacs";
    nix-doom-emacs.flake = false;
    doomPrivateDir.url = "/path/to/doom.d";
    doomPrivateDir.flake = false;
  };

  outputs = { self, home-manager, nix-doom-emacs, doomPrivateDir, ... }: {
    nixosConfigurations.exampleHost = {
      imports = [ home-manager.nixosModules.home-manager ];

      home-manager.users.exampleUser = { pkgs, ... }: {
        home.packages.emacs = {
            enable = true;
            package = pkgs.callPackage nix-doom-emacs { inherit doomPrivateDir; };
        };
      };
    };
  };
}
```

**Comment by vlaci** [comment]
I think the issue is that I am using the string value of `doomPrivateDir` (which points outside of the nix store) in https://github.com/vlaci/nix-doom-emacs/blob/7b0bfa990062e1aad527ac7ca150177f8b1a683a/default.nix#L85 to make `doom/open-private-config (SPC f p)` work.
If I patch out this, then the above mentioned workaround is not needed. (putting `doomPrivateDir` in the `inputs` attrset breaks this feature anyway...).

I'll experiment a bit more with path handling as I really like this functionality.

**Comment by vlaci** [comment]
There is a new `flake` branch where I experiment with `flake.nix support. It contains a home-manager modules as well.

https://github.com/vlaci/nix-doom-emacs/blob/flake/flake.nix

**Comment by vlaci** [comment]
The simplest workaround for now is to wrap `doomPrivateDir` argument in another path, e.g:
```nix
pkgs.callPackage nix-doom-emacs { doomPrivateDir = builtins.path { path = ./path/to/doom.d; }; }
```

**Comment by pltanton** [comment]
DISCLAIMER: I'm not an expert, so all what I'm saying might be wrong.

```
  doom-emacs = pkgs.callPackage inputs.nixDoomEmacs { doomPrivateDir = ./doom.d; };
```

As far as I know if I use `./doom.d` (without quotes) it should be represented to nix as a path, not a string. Therefore, it should already be in store. So I don't get the difference the trick with `builtins.path { path = ... }` makes. By the way I test this workaround and it works perfectly.

**Comment by vlaci** [comment]
Path literals are resolved to a store path when used in a string context but you can recover the original absolute path it is pointing to via `tostring`. AFIK this wrapper ensures that this can no longer be done.

**Comment by vlaci** [comment]
The workaround is integrated on master as part of the flake support.
