### ISSUE TITLE
Bug in rust mode

### ISSUE THREAD

**Issue by happysalada** [vlaci/nix-doom-emacs#63]
I'm getting a bug in rust that was fixed in this PR
https://github.com/hlissner/doom-emacs/pull/3478

How do I make sure to get the right version. Is it a matter of selecting the develop branch?

**Comment by vlaci** [comment]
Do you use the bundled version of emacs packages? I have checked and the mentioned fix has been included in the bundled emacs-mirror revision for some time.

**Comment by happysalada** [comment]
I am not sure what you are refering to.
The way I install doom-emacs is that I just add that at the top of my home-manager config file
```
let
  doom-emacs = pkgs.callPackage (builtins.fetchTarball {
    url = "https://github.com/vlaci/nix-doom-emacs/archive/master.tar.gz";
  }) {
    doomPrivateDir = ./doom.d; # Directory containing your config.el init.el
    emacsPackagesOverlay = self: super: {
      magit-delta = super.magit-delta.overrideAttrs
        (esuper: { buildInputs = esuper.buildInputs ++ [ pkgs.git ]; });
    };
  };
```

**Comment by vlaci** [comment]
I have cheched that `rust-flycheck-clippy params` is available in my build via loading up `rustic` mode and issuing `SPC h v rustic-flycheck-clippy params` tells me:
```rustic-flycheck-clippy-params is a variable defined in
rustic-flycheck.el.

Value
"--message-format=json -Zunstable-options"

```

**Comment by happysalada** [comment]
@vlaci Sorry about this issue.
I had a misconfiguration in my direnv plugin.

I learned that with `doom/info` you can check the build version (I didn't know if I was running the latest version). It shows the emacs version and part of the doom version.

Sorry again!
