### ISSUE TITLE
Using the daemon

### ISSUE THREAD

**Issue by happysalada** [vlaci/nix-doom-emacs#64]
I am wondering how to use this with the emacs daemon.

I see there is an option on NixOs to enable the emacs daemon
https://daiderd.com/nix-darwin/manual/index.html#opt-services.emacs.enable
(I'm referring to nix-darwin, but it's the same option in nixos)

Has anybody successfully managed to use it?

I'm wondering if it installs another emacs when you enable that option.
https://search.nixos.org/options?show=services.emacs.enable&query=emacs&from=0&size=30&sort=relevance&channel=unstable#disabled
It wouldn't be too bad if it was the case, just curious.

Also I link with this guy's config to having a systemd process to handle the emacs daemon
https://tecosaur.github.io/emacs-config/config.html#systemd-daemon

Perhaps this doesn't belong here. I'm just curious if anybody is using the daemon, so perhaps it can be documented.

**Comment by vlaci** [comment]
There is a `services.emacs.package` otpion you need to set to refer to `nix-doom-emacs` derivation. I have yet to try how it works though.

**Comment by vlaci** [comment]
Daemon mode works fine for me with the above option. Feel free to reopen if you have any issues.
