### ISSUE TITLE
Cannot open load file: No such file or directory, mu4e

### ISSUE THREAD

**Issue by JonathanReeve** [vlaci/nix-doom-emacs#66]
When trying to launch mu4e, I get: "Cannot open load file: No such file or directory, mu4e."

**Comment by vlaci** [comment]
Have you tried specifying `extraPackages` as in this example? 
https://github.com/vlaci/nix-doom-emacs/blob/f322ca116373b7aead49ed574468048e76638a9c/default.nix#L9

**Comment by JonathanReeve** [comment]
That did the trick! Thanks!
