### ISSUE TITLE
Ability to override emacs base package in hmModule.

### ISSUE THREAD

**Issue by pltanton** [vlaci/nix-doom-emacs#78]
The new hmModule in flake branch is great. 

It would be amazing feature to be able to override the base emacs package in the way, that it done in other modules of home-manager. 
For example, I prefer to use emacs-pgtk package from packagesWayland flake, because it is native for wayland and default emacs package causes crashes of sway for some reason.

**Comment by vlaci** [comment]
This is now available on master.

**Comment by pltanton** [comment]
You are amazing, thanks!
