### ISSUE TITLE
all the icons fonts not displaying after including

### ISSUE THREAD

**Issue by codygman** [vlaci/nix-doom-emacs#8]
I [added emacs-all-the-icons-font](https://github.com/codygman/my-emacs-everywhere/blob/37185798b47d090073447c93a3c3e389861b9222/nixpkgs/doomemacs.nix#L7) to `nix-doom-emacs.extraPackages` and the fonts are still not displaying.

**Comment by vlaci** [comment]
If you use NixOS then unfortunately you need to install these fonts the usual way. Try putting
```nix
{
  fonts.fonts = [ pkgs.emacs-all-the-icons-fonts ];
}
```
in your `configuration.nix`

**Comment by codygman** [comment]
I need to test this works from a new vm later, then I'll close this if that's okay with you.
