### ISSUE TITLE
can't find program when using emacsclient

### ISSUE THREAD

**Issue by happysalada** [vlaci/nix-doom-emacs#89]
I use `gitAndTools.delta` additionally in magit to show simpler diffs.
When I use the normal emacs (started with `emacs .`, then I have no problem.
When I use `emacsclient -c`, then I get `can't find program delta`
Is there something that I need to do to make delta accessible inside the daemon?

**Comment by vlaci** [comment]
When emacs started as a service, the startup job first sources `/etc/set-environment` on NixOS. It sets the value of PATH to this value on my system:
```export PATH="$HOME/.nix-profile/bin:/etc/profiles/per-user/$USER/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"```
Where is `delta` installed on your system, e.g what does `which delta` output? Can you still use it in an interactive terminal if you first source `/etc/set-environment`?

**Comment by happysalada** [comment]
Thanks a lot for taking a look at this!
You're right, it is a path issue.
On macos the default path is something like `/usr/bin:/bin` but nix-darwin adjusts that for terminals to what it should be. It looks like for services that adjustment isn't being made.

I'm not aware of how to adjust the path for a service.
I guess this is more of a nix-darwin problem than it is a doom emacs.
I'm going to close this for now.
